"""Russian single-page operator UI; credentials exist only in page memory."""
from .panel_ui import STYLE as BASE_STYLE

PAGE = """<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>USB Device Lab — тестирование</title><link rel="stylesheet" href="/workspace.css"></head><body><main class="shell">
<header><h1>Управление фаззером</h1><p class="subtitle">Кампании, результаты и логи в одном месте.</p></header>
<section id="login" class="glass panel"><label for="access">Токен доступа</label><input id="access" type="password" autocomplete="off"><button id="enter">Войти</button><p class="hint">Токен остаётся только в памяти этой страницы. После её закрытия войдите снова. Выход из панели не останавливает кампанию.</p></section>
<div id="app" hidden><div class="toolbar"><label>Просмотр кампании <select id="campaign"></select></label><button id="exit">Выйти</button><span id="updated"></span></div><p id="notice" role="status" aria-live="polite"></p>
<nav class="actions" aria-label="Разделы"><button data-tab="manage">Управление</button><button data-tab="results" id="results-tab">Результаты</button><button data-tab="logs">Логи</button><button data-tab="corpus">Корпус</button></nav>
<section data-page="manage" class="glass panel"><h2>Настройки новой кампании</h2><dl id="configured"></dl><p class="hint">Настройки взяты из lab.toml. Чтобы изменить их, отредактируйте файл.</p><button id="start" class="primary">Запустить новую кампанию</button><h2>Ход текущей кампании</h2><p id="progress"></p><dl id="active"></dl><div class="actions"><button id="stop">Остановить после текущей попытки</button><button id="resume">Продолжить кампанию</button></div><p class="hint">Продолжение использует сохранённое состояние. При изменении настроек оно будет запрещено.</p></section>
<section data-page="results" class="glass panel" hidden><h2>Сообщения об ошибках ядра</h2><div id="kernel-errors"></div><h2>Ошибки стенда и исполнителя</h2><div id="other-errors"></div><h2>Попытки выбранной кампании</h2><p class="hint">Показаны последние 100 попыток и отдельно последние 100 попыток с ошибками.</p><div class="table-wrap"><table><thead><tr><th>Попытка</th><th>Начало</th><th>Результат</th><th>Новые точки покрытия</th><th></th></tr></thead><tbody id="rows"></tbody></table></div></section>
<section data-page="logs" class="glass panel" hidden><h2>Логи и файлы попытки</h2><label>Попытка <select id="attempt"></select></label><label>Источник <select id="source"><option value="executor">Исполнитель</option><option value="agent">Агент на хосте</option><option value="kernel">Сообщения ядра</option></select></label><div class="actions"><button id="pause">Приостановить обновление</button><button id="bottom">К последним сообщениям</button><button id="download-log">Скачать этот лог</button></div><p id="log-note"></p><pre id="log-text" tabindex="0"></pre><h3>Файлы выбранной попытки</h3><div id="downloads" class="actions"></div><p class="hint">На экране — последние 200 строк, не более 64 КиБ. Скачивается весь доступный файл до 64 МиБ, без усечения. Сообщения ядра доступны после сохранения агентом.</p></section>
<section data-page="corpus" class="glass panel" hidden><h2>Корпус стенда</h2><select id="corpus-source"><option value="seeds">Исходные устройства</option><option value="learned">Корпус кампаний, включая исходные устройства</option></select><label>Семейство <select id="corpus-family"><option value="">Все семейства</option></select></label><label>Профиль <select id="corpus-profile"><option value="">Все профили</option></select></label><div id="cards" class="metrics"></div><button id="corpus-next">Следующая порция</button><pre id="config-detail"></pre></section>
</div><p id="connection" role="status" aria-live="polite"></p></main><script src="/workspace.js"></script></body></html>
""".encode("utf-8")
SCRIPT = r""" 'use strict';
const el=id=>document.getElementById(id);let token='',epoch=0,abort=new AbortController(),busy=false,paused=false,actionFailure='',selected='',follow=true,corpusOffset=0,corpusNext=0;
const stateNames={idle:'Ожидание',starting:'Проверяем стенд и запускаем',running:'Выполняется',stopping:'Завершаем текущую попытку',stopped:'Остановлена',completed:'Завершена',failed:'Остановлена из-за ошибки',interrupted:'Прервана'};
const outcomes={kernel_candidate:'Сообщение об ошибке ядра — требует проверки',new_coverage:'Новое покрытие',no_change:'Без изменений',infrastructure_failure:'Ошибка стенда',executor_failure:'Ошибка исполнителя',inconclusive:'Недостаточно данных',legacy_unclassified:'Старый запуск без итоговой оценки',running:'Выполняется',interrupted:'Прерван',unclassified_failure:'Ошибка выполнения'};
const families={hid:'Устройства ввода',audio:'Звуковые устройства',cdc:'Последовательный порт и сеть',storage:'Накопители',midi:'Музыкальные устройства',uvc:'Камеры',composite:'Составные устройства',boundary:'Граничные конфигурации',unknown:'Не указано'};
const profiles={keyboard:'Клавиатура',mouse:'Мышь',gamepad:'Игровой контроллер','consumer-control':'Мультимедийные кнопки','multi-report':'Несколько отчётов','uac1-playback':'Воспроизведение звука','uac1-capture':'Запись звука','uac1-duplex':'Запись и воспроизведение',acm:'Последовательный порт',ecm:'Сетевой интерфейс','bulk-only':'Накопитель','midi-streaming':'Музыкальный интерфейс',streaming:'Камера','hid-cdc':'Устройства ввода и последовательный порт','hid-audio':'Устройства ввода и звук','hid-storage':'Устройства ввода и накопитель','multi-config':'Несколько конфигураций','multi-altsetting':'Несколько вариантов интерфейса','endpoint-matrix':'Набор конечных точек',unknown:'Не указано'};
const files={'executor.log':'Лог исполнителя','agent.log':'Лог агента','kmsg.delta.log':'Сообщения ядра','config.json':'Конфигурация устройства','input.executed.json':'Снимок входной конфигурации','metadata.json':'Параметры и история мутаций','result.json':'Полный результат'};
function text(tag,value){const node=document.createElement(tag);node.textContent=String(value);return node;}
function showTab(name){for(const page of document.querySelectorAll('[data-page]'))page.hidden=page.dataset.page!==name;for(const button of document.querySelectorAll('[data-tab]'))button.setAttribute('aria-selected',String(button.dataset.tab===name));}
for(const button of document.querySelectorAll('[data-tab]'))button.addEventListener('click',()=>showTab(button.dataset.tab));
async function api(path,options={}){const generation=epoch;const response=await fetch(path,{...options,signal:abort.signal,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json();if(generation!==epoch)throw new Error('Данные больше не актуальны.');if(!response.ok)throw new Error(({400:'Не удалось прочитать данные. Проверьте настройки.',401:'Токен не принят. Войдите снова.',403:'Проверьте адрес панели.',404:'Файл пока не готов.',503:'Данные временно недоступны.'}[response.status])||data.error||'Не удалось получить данные.');return data;}
function settings(node,data){node.replaceChildren();for(const [label,value] of [['Количество попыток',data.iterations],['Длительность попытки, секунд',data.seconds],['Начальное значение генератора',data.seed],['Устройства',data.families.length?data.families.map(x=>families[x]||'Пользовательское семейство').join(', '):'Все выбранные в конфигурации']])node.append(text('dt',label),text('dd',value));}
function updateCampaigns(data){const keep=follow?(data.current||(['starting'].includes(data.status)?'':el('campaign').value||selected)):el('campaign').value||selected;el('campaign').replaceChildren();for(const campaign of data.campaigns){const option=document.createElement('option');option.value=campaign.id;option.textContent=campaign.id==='legacy'?'Ранее сохранённые попытки':(campaign.started?new Date(campaign.started*1000).toLocaleString('ru-RU'):'Новая кампания')+' · завершено '+campaign.done;el('campaign').append(option);}el('campaign').value=keep;if(!el('campaign').value&&el('campaign').options.length&&data.status!=='starting')el('campaign').selectedIndex=0;selected=el('campaign').value;}
function logButton(row){const button=text('button','Открыть логи');button.addEventListener('click',()=>{el('attempt').value=row.id;showTab('logs');loadLogs().catch(report);});return button;}
function updateAttempts(rows){const keep=el('attempt').value||'auto',old=el('attempt').selectedOptions[0]?.textContent;el('attempt').replaceChildren();const automatic=text('option','Текущая или последняя попытка');automatic.value='auto';el('attempt').append(automatic);for(const row of rows){const option=text('option',(Number.isInteger(row.iteration)?'№'+(row.iteration+1):'Попытка')+' · '+new Date(row.started*1000).toLocaleTimeString('ru-RU')+' · '+(outcomes[row.outcome]||'Результат сохранён'));option.value=row.id;el('attempt').append(option);}if(keep!=='auto'&&!rows.some(x=>x.id===keep)){const option=text('option',old||'Ранее выбранная попытка');option.value=keep;el('attempt').append(option);}el('attempt').value=keep;el('attempt').dataset.latest=rows[0]?.id||'';}
function renderResults(data){updateAttempts(data.rows);el('rows').replaceChildren();for(const row of data.rows){const tr=document.createElement('tr');for(const value of [Number.isInteger(row.iteration)?'№'+(row.iteration+1):'Ранее сохранённая',new Date(row.started*1000).toLocaleString('ru-RU'),outcomes[row.outcome]||'Результат сохранён',row.new_pcs??'—'])tr.append(text('td',value));const actions=document.createElement('td');actions.append(logButton(row));tr.append(actions);el('rows').append(tr);}const opened=new Set([...document.querySelectorAll('details[open]')].map(x=>x.dataset.key));el('kernel-errors').replaceChildren();el('other-errors').replaceChildren();for(const row of data.errors){const kernel=row.kernel_events.length>0,container=el(kernel?'kernel-errors':'other-errors');const card=document.createElement('article');card.className='error-card';card.append(text('h3',kernel?'Сообщение об ошибке ядра — требует проверки':'Ошибка стенда или исполнителя'),text('p',(Number.isInteger(row.iteration)?'Попытка №'+(row.iteration+1):'Ранее сохранённая попытка')+' · '+new Date(row.started*1000).toLocaleString('ru-RU')));const details=document.createElement('details');details.dataset.key=row.id;details.open=opened.has(row.id);details.append(text('summary','Исходные сообщения'),text('pre',JSON.stringify(kernel?row.kernel_events:row.errors,null,2)));card.append(details,logButton(row));container.append(card);}for(const id of ['kernel-errors','other-errors'])if(!el(id).children.length)el(id).append(text('p','Сообщений об ошибках нет.'));el('results-tab').textContent='Результаты'+(data.errors.length?' · ошибок: '+data.errors.length:'');}
function runId(){return el('attempt').value==='auto'?el('attempt').dataset.latest:el('attempt').value;}
async function download(name){const generation=epoch,run=runId();if(!selected||!run){report(new Error('Сначала выберите попытку.'));return;}try{const q=new URLSearchParams({campaign:selected,run,name});const response=await fetch('/api/workspace/file?'+q,{headers:{Authorization:'Bearer '+token},signal:abort.signal});if(!response.ok){const data=await response.json();throw new Error(({401:'Токен не принят. Войдите снова.',403:'Доступ к файлу запрещён.',404:'Файл пока не готов.'}[response.status])||data.error||'Не удалось скачать файл.');}const blob=await response.blob();if(generation!==epoch)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=run.slice(0,8)+'-'+name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){if(generation===epoch)report(error);}}
for(const [name,label] of Object.entries(files)){const button=text('button',label);button.addEventListener('click',()=>download(name));el('downloads').append(button);}
async function loadLogs(){if(!selected||!runId()){el('log-note').textContent='Попытки ещё не начались.';return;}const q=new URLSearchParams({campaign:selected,run:runId(),source:el('source').value});try{const data=await api('/api/workspace/tail?'+q);const output=el('log-text'),atBottom=output.scrollHeight-output.scrollTop-output.clientHeight<30,position=output.scrollTop;if(output.textContent!==data.text){output.textContent=data.text;output.scrollTop=atBottom?output.scrollHeight:position;}el('log-note').textContent=(data.text?'Последние сообщения':'Лог пока пуст')+(data.truncated?' · показан ограниченный хвост':'')+(data.saved_kernel_log?' · сохранённый файл сообщений ядра':'');}catch(error){el('log-note').textContent=humanError(error);}}
async function loadCorpus(){const q=new URLSearchParams({source:el('corpus-source').value,offset:corpusOffset,family:el('corpus-family').value,profile:el('corpus-profile').value});const data=await api('/api/corpus?'+q);el('cards').replaceChildren();for(const item of data.items){const card=document.createElement('article');card.className='glass panel';card.append(text('h3',(families[item.family]||'Пользовательское семейство')+' · '+(profiles[item.profile]||'Пользовательский профиль')));if(item.valid){card.append(text('p','Дескрипторов: '+item.descriptor_count+'; интерфейсов: '+item.interface_count));const button=text('button','Открыть конфигурацию');button.addEventListener('click',async()=>{try{const value=await api('/api/corpus/'+item.source+'/'+item.id);el('config-detail').textContent=JSON.stringify(value.config,null,2);}catch(error){report(error);}});card.append(button);}else card.append(text('p','Конфигурация недоступна.'));el('cards').append(card);}corpusNext=data.next_offset;el('corpus-next').disabled=!data.more;}
function humanError(error){return ['TypeError','SyntaxError'].includes(error.name)?'Не удалось получить ответ сайта. Проверьте соединение.':error.message||'Не удалось выполнить запрос.';}
function report(error){if(error.name!=='AbortError'&&token){actionFailure=humanError(error);el('notice').textContent=actionFailure;}}
async function refresh(){if(!token||busy)return;busy=true;const generation=epoch;try{const data=await api('/api/workspace/status');if(generation!==epoch)return;settings(el('configured'),data.configured);settings(el('active'),data.active);el('active').hidden=!data.has_history;el('progress').textContent=data.status==='idle'?'Кампания не запущена.':(stateNames[data.status]||'Нет данных')+' · выполнено '+data.completed+' из '+data.active.iterations+' · осталось '+Math.max(0,data.active.iterations-data.completed);el('notice').textContent=actionFailure||data.failure||(data.restart_required?'Настройки стенда изменились. Перезапустите сайт.':'');updateCampaigns(data);const running=['starting','running','stopping'].includes(data.status);el('start').disabled=running||data.restart_required;el('resume').disabled=running||data.completed>=data.active.iterations||Boolean(selected&&data.current&&selected!==data.current);el('stop').disabled=!running||Boolean(selected&&data.current&&selected!==data.current);if(selected)renderResults(await api('/api/workspace/runs?'+new URLSearchParams({campaign:selected})));if(!paused)await loadLogs();await loadCorpus();el('updated').textContent='Обновлено '+new Date().toLocaleTimeString('ru-RU');el('connection').textContent='';}catch(error){if(generation===epoch)el('connection').textContent=error.name==='AbortError'?'':'Не удалось обновить данные. '+humanError(error);}finally{if(generation===epoch)busy=false;}}
async function command(action){if(action==='start'&&!confirm('Запустить новую кампанию с настройками из lab.toml?'))return;actionFailure='';try{await api('/api/workspace/'+action,{method:'POST',body:'{}'});if(action!=='stop'){follow=true;selected='';el('campaign').replaceChildren();}await refresh();}catch(error){report(error);}}
el('enter').addEventListener('click',async()=>{token=el('access').value.trim();if(!token){el('connection').textContent='Введите токен.';return;}try{await api('/api/workspace/status');el('access').value='';el('login').hidden=true;el('app').hidden=false;await refresh();}catch(error){token='';el('connection').textContent='Не удалось войти. '+humanError(error);}});
el('exit').addEventListener('click',()=>{epoch++;abort.abort();abort=new AbortController();token='';busy=false;actionFailure='';selected='';el('app').hidden=true;el('login').hidden=false;for(const id of ['rows','kernel-errors','other-errors','cards','campaign','attempt','configured','active'])el(id).replaceChildren();for(const id of ['log-text','config-detail','notice','connection','progress','updated','log-note'])el(id).textContent='';});
el('campaign').addEventListener('change',()=>{selected=el('campaign').value;follow=false;el('attempt').value='auto';el('log-text').textContent='';refresh();});el('attempt').addEventListener('change',()=>loadLogs().catch(report));el('source').addEventListener('change',()=>loadLogs().catch(report));el('pause').addEventListener('click',()=>{paused=!paused;el('pause').textContent=paused?'Продолжить обновление':'Приостановить обновление';});el('bottom').addEventListener('click',()=>{el('log-text').scrollTop=el('log-text').scrollHeight;});el('download-log').addEventListener('click',()=>download({executor:'executor.log',agent:'agent.log',kernel:'kmsg.delta.log'}[el('source').value]));for(const action of ['start','stop','resume'])el(action).addEventListener('click',()=>command(action));el('corpus-source').addEventListener('change',()=>{corpusOffset=0;loadCorpus().catch(report);});el('corpus-next').addEventListener('click',()=>{corpusOffset=corpusNext;loadCorpus().catch(report);});showTab({results:'results',logs:'logs',corpus:'corpus'}[location.pathname.slice(1)]||'manage');setInterval(refresh,3000);

for(const [id,values] of [['corpus-family',families],['corpus-profile',profiles]]){for(const [value,label] of Object.entries(values)){const option=text('option',label);option.value=value;el(id).append(option);}el(id).addEventListener('change',()=>{corpusOffset=0;loadCorpus().catch(report);});}
""".encode("utf-8")
STYLE = BASE_STYLE + b'[hidden]{display:none!important}.toolbar{display:flex;gap:14px;align-items:center;flex-wrap:wrap;margin:20px 0}select{background:#14263d;color:#edf4ff;padding:10px;border:1px solid var(--border);border-radius:10px}nav{margin:24px 0}button[aria-selected=true]{border-color:var(--accent)}dl{display:grid;grid-template-columns:1fr 1fr;gap:8px}dt{color:var(--muted)}dd{margin:0}.error-card{padding:16px;margin:12px 0;border:1px solid #754457;border-radius:14px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid var(--border)}.table-wrap{overflow:auto}#log-text{height:340px;max-height:65vh;overflow:auto;white-space:pre-wrap}#connection{color:#ffc9d3}'
